codecov:
    require_ci_to_pass: true

coverage:
    status:
        project:
            uikit:
                target: 80%
                threshold: 0%
                base: auto
                paths:
                    - "src/shared"
                if_ci_failed: error
                informational: false
                only_pulls: false
        patch:
            uikit:
                target: 80%
                threshold: 0%
                base: auto
                paths:
                    - "src/shared"
                if_ci_failed: error
                informational: false
                only_pulls: false
comment:
    layout: "reach, diff, flags, files"
    behavior: default
    require_changes: false
    require_base: false        # [yes :: must have a base report to post]
    require_head: true       # [yes :: must have a head report to post]
