export const CLOSE_DROPDOWN = 'CLOSE_DROPDOWN'
export const TOGGLE_TIMING_TOAST = 'TOGGLE_TIMING_TOAST'
export const TOGGLE_TOAST = 'TOGGLE_TOAST'
export const CLOSE_INNER_DROPDOWN = 'CLOSE_INNER_DROPDOWN'
