export { default as errorPageShape } from './errorPageShape'
export { default as stepsShape } from './stepsShape'
export { default as paginationShape } from './paginationShape'
export { default as legendShape } from './legendShape'
export { default as scrollSpyShape } from './scrollSpyShape'
