on: "pull_request"

jobs:
    frontend:
        runs-on: ubuntu-20.04
        if: "contains(github.event.comment.body, '[deploy]')"
        steps:
        - uses: actions/checkout@v2

        - name: Setup Nodejs with yarn caching
          uses: actions/setup-node@v2
          with:
            node-version: "14.18.0"
            cache: yarn

        - name: Install
          run: yarn install

        - name: Lint
          run: yarn lint

        - name: Test
          run: yarn test --coverage


        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v2
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
