name: Deploy styleguide to S3
on:
  push:
    branches:
#      - master
      - OP-1123-GHA-bump-deprecated-gha

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::084824767965:role/gha-ui-kit
          role-duration-seconds: 3600
          aws-region: eu-west-1
          role-session-name: gha-ui-kit

      - run: aws sts get-caller-identity

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache-dependency-path: pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.12

      - name: Install dependencies
        run: pnpm install

      - name: Build and export Storybook
        run: pnpm build-storybook

      # - name: Deploy to S3
      #   run:
      #     aws s3 sync ./storybook-static/ s3://styleguide.landingi.com --delete
